apiVersion: apps/v1
kind: Deployment
metadata:
  name: snekbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snekbox
  template:
    metadata:
      labels:
        app: snekbox
    spec:
      containers:
        - name: snekbox
          image: ghcr.io/python-discord/snekbox:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          securityContext:
            privileged: true
          volumeMounts:
            - name: snekbox-user-base-volume
              mountPath: /snekbox/user_base
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - >-
                    find /lang/python -mindepth 1 -maxdepth 1 -type d -exec
                    sh -c 'PYTHONUSERBASE=/snekbox/user_base &&
                    {}/bin/python -m pip install --user -U
                    anyio[trio]~=3.6
                    arrow~=1.2
                    attrs~=22.2
                    beautifulsoup4~=4.11
                    einspect~=0.5
                    fishhook~=0.2
                    forbiddenfruit~=0.1
                    fuzzywuzzy~=0.18
                    lark~=1.1
                    "matplotlib~=3.6 ; python_version == \'3.11\'"
                    more-itertools~=9.0
                    networkx~=3.0
                    "numpy~=1.24 ; python_version == \'3.11\'"
                    "numpy==1.26.0b1 ; python_version == \'3.12\'"
                    "pandas~=1.5 ; python_version == \'3.11\'"
                    "pendulum~=2.1 ; python_version == \'3.11\'"
                    python-dateutil~=2.8
                    pyyaml~=6.0
                    scipy~=1.10
                    sympy~=1.11
                    toml~=0.10
                    typing-extensions~=4.4
                    tzdata~=2022.7
                    "yarl~=1.8 ; python_version == \'3.11\'"
                    ' \;
      volumes:
        - name: snekbox-user-base-volume
          hostPath:
            path: /snekbox_dep_cache
            type: DirectoryOrCreate
