version: "3.7"

services:
  snekbox:
    container_name: snekbox
    privileged: true
    image: ghcr.io/python-discord/snekbox:latest
    ports:
     - 8060:8060
    init: true
    ipc: none
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - user-base:/snekbox/user_base

volumes:
  user-base:
